# Generated by Django 3.1.1 on 2020-10-03 14:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/users/team-1.jpg', upload_to='media/users'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
