# Generated by Django 3.1.1 on 2020-10-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20201003_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employee',
        ),
    ]
