# Generated by Django 3.1.1 on 2020-10-03 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0008_remove_job_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employee',
            field=models.ManyToManyField(blank=True, default=None, related_name='job_apply', to=settings.AUTH_USER_MODEL),
        ),
    ]
